name: stickers
description: "A minimal WhatsApp sticker maker"

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.3.0+15

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  animations: ^2.0.11
  characters: ^1.4.0
  image_picker: ^1.1.2
  package_info_plus: 8.3.0
  path_provider: ^2.1.5
  share_handler: ^0.0.22
  shared_preferences: ^2.5.3
  vector_math: ^2.1.4
  share_plus: ^11.0.0
  file_picker: ^10.1.9
  flutter_launcher_icons: ^0.14.3
  url_launcher: ^6.3.1

  # Custom packages that have been modified
  matrix_gesture_detector:
    git:
      url: https://github.com/lolocomotive/matrix_gesture_detector
      ref: 62749b7e18f6a61834ca7f5bb45f9c7ace12bdd2
  extended_image:
    git:
      url: https://github.com/lolocomotive/extended_image
      ref: 9a0a7a577c29519d3535b14db95922bb0d53b78c
  image_editor:
    git:
      url: https://github.com/lolocomotive/flutter_image_editor
      ref: e848b10f7be0e78dc89b0907b92859b66a12144e
      path: image_editor
  whatsapp_stickers_plus:
    git:
      url: https://github.com/lolocomotive/whatsapp_stickers_plus
      ref: c435f986166c5734b1d64561307cad619814f531
  flutter_archive:
    git:
      url: https://github.com/lolocomotive/flutter_archive
      ref: 555a589a0b4def2641f02e5352f4b842ccf9164d
  video_player: ^2.10.0
  restart_app: ^1.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true
  shaders:
    - assets/shaders/hue_gradient.frag
    - assets/shaders/saturation_gradient.frag
    - assets/shaders/lightness_gradient.frag
  assets:
    - assets/fonts/OFL.txt
    - assets/transparent.webp
  fonts:
    - family: Passions Conflict
      fonts:
        - asset: assets/fonts/Passions Conflict.ttf
    - family: Island Moments
      fonts:
        - asset: assets/fonts/Island Moments.ttf
    - family: Saira Stencil One
      fonts:
        - asset: assets/fonts/Saira Stencil One.ttf
    - family: Sacramento
      fonts:
        - asset: assets/fonts/Sacramento.ttf
    - family: Unifraktur Maguntia
      fonts:
        - asset: assets/fonts/Unifraktur Maguntia.ttf
    - family: DM Serif Text
      fonts:
        - asset: assets/fonts/DM Serif Text.ttf
    - family: Lobster
      fonts:
        - asset: assets/fonts/Lobster.ttf
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico.ttf
    - family: Press Start 2P
      fonts:
        - asset: assets/fonts/Press Start 2P.ttf
    - family: Racing Sans One
      fonts:
        - asset: assets/fonts/Racing Sans One.ttf
    - family: Roboto Mono
      fonts:
        - asset: assets/fonts/Roboto Mono.ttf